### ISSUE TITLE
Mobile Functionality? 

### ISSUE THREAD

**Issue by heathyates** [leandrobrunner/jquery-overlap#2]
Are you aware of any jquery that provides the same functionality, but for touch events as well? 

For example, consider your demo. It is a grid and you use the mouse to draw a square and select the white squares making them blue. What about similar functionality for touch? 

Rather than having to draw a square with my finger, I would like to take my finger and drag (touchmove) it across the squares selecting multiple squares. Can this current code be extended to support that or do you know of any code that already does this? 

Thanks for your time.

**Comment by leandrobrunner** [comment]
Hello\* heathyates*, Thank you very much for your recommendation,

If you look, my code simply selected the items in certain area,
in the example only I implemented mouse events, but integrate touch
events is practically the same.

The touch events not depend of my plugin, but of the implementation of each.

Then I integrate touch events to the example. ;)

Greetings. :)
Leandro

**Comment by heathyates** [comment]
Thanks for your informative reply. :-)
